# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esmiapp', '0002_auto_20161213_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esminews',
            name='typeartical',
            field=models.CharField(choices=[('c', 'close'), ('f', 'free')], help_text='Тип материала', max_length=1),
        ),
        migrations.AlterModelTable(
            name='esmiislikedissue',
            table='esmi_likedissue',
        ),
    ]
